# Generated by Django 3.0.7 on 2020-06-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200620_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='サイトの説明を書いてください。また、このモデルは追加をしても意味がないのでご了承ください。', verbose_name='本文')),
            ],
            options={
                'verbose_name': 'プライバシーポリシー',
                'verbose_name_plural': 'プライバシーポリシー',
            },
        ),
        migrations.AlterField(
            model_name='site',
            name='content',
            field=models.TextField(help_text='サイトの説明を書いてください。また、このモデルは追加をしても意味がないのでご了承ください。', verbose_name='本文'),
        ),
    ]
